AWSTemplateFormatVersion: 2010-09-09 #optionel
Resources:
  Bucket_S3:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: STD21084
      AccessControl: Public
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: MyS3Bucket
  MyParameterS3:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/my/parameter"
      Type: "String"
      Value: !Join [ "", ["arn:aws:s3:::", !Ref Bucket_S3] ]

