AWSTemplateFormatVersion: 2010-09-09 #optionel
Resources:
  Bucket_S3:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: STD21084
      AccessControl: Public
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: MyS3Bucket
