AWSTemplateFormatVersion: 2010-09-09 #optionel
Resources:
  Bucket_S3:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: STD21084
      AccessControl: Public
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: MyS3Bucket
  
  BucketSSMParameters:
    My_S3_Parameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /S3_Parameter/arn
        Type: String
        Value: !GetAtt Bucket_S3.Arn
